{
 "title": "Feedback RAG Monitoring",
 "description": "Feedback RAG Monitoring for AviMate Flight Assistant",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Conversations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from conversations ; "
    }
   ]
  },
  {
   "title": "Conversations with Feedback",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(conversations.id) from conversations inner join feedback on conversations.id = feedback.conversation_id"
    }
   ]
  },
  {
   "title": "Feedback Count",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count(id), feedback FROM feedback\r\ngroup BY feedback; "
    }
   ]
  },
  {
   "title": "Recent 5 Conversations",
   "type": "table",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT c.timestamp, c.id, c.question, c.answer, f.feedback FROM conversations c\r\nleft join feedback f on c.id = f.conversation_id\r\norder by c.timestamp desc\r\nLIMIT 5"
    }
   ]
  }
 ]
}